/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PdfFile } from "./PdfFile";
import { PdfFileCountArgs } from "./PdfFileCountArgs";
import { PdfFileFindManyArgs } from "./PdfFileFindManyArgs";
import { PdfFileFindUniqueArgs } from "./PdfFileFindUniqueArgs";
import { CreatePdfFileArgs } from "./CreatePdfFileArgs";
import { UpdatePdfFileArgs } from "./UpdatePdfFileArgs";
import { DeletePdfFileArgs } from "./DeletePdfFileArgs";
import { PdfPageFindManyArgs } from "../../pdfPage/base/PdfPageFindManyArgs";
import { PdfPage } from "../../pdfPage/base/PdfPage";
import { PdfFileCreateInput } from "./PdfFileCreateInput";
import { PdfFileUpdateInput } from "./PdfFileUpdateInput";
import { PdfFileUpdatePascalInput } from "../PdfFileUpdatePascalInput";
import { PdfFileService } from "../pdfFile.service";
@graphql.Resolver(() => PdfFile)
export class PdfFileResolverBase {
  constructor(protected readonly service: PdfFileService) {}

  async _pdfFilesMeta(
    @graphql.Args() args: PdfFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PdfFile])
  async pdfFiles(
    @graphql.Args() args: PdfFileFindManyArgs
  ): Promise<PdfFile[]> {
    return this.service.pdfFiles(args);
  }

  @graphql.Query(() => PdfFile, { nullable: true })
  async pdfFile(
    @graphql.Args() args: PdfFileFindUniqueArgs
  ): Promise<PdfFile | null> {
    const result = await this.service.pdfFile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PdfFile)
  async createPdfFile(
    @graphql.Args() args: CreatePdfFileArgs
  ): Promise<PdfFile> {
    return await this.service.createPdfFile({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => PdfFile)
  async updatePdfFile(
    @graphql.Args() args: UpdatePdfFileArgs
  ): Promise<PdfFile | null> {
    try {
      return await this.service.updatePdfFile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PdfFile)
  async deletePdfFile(
    @graphql.Args() args: DeletePdfFileArgs
  ): Promise<PdfFile | null> {
    try {
      return await this.service.deletePdfFile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PdfPage], { name: "pdfPages" })
  async findPdfPages(
    @graphql.Parent() parent: PdfFile,
    @graphql.Args() args: PdfPageFindManyArgs
  ): Promise<PdfPage[]> {
    const results = await this.service.findPdfPages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.Mutation(() => PdfFileCreateInput)
  async AddPdfFile(
    @graphql.Args()
    args: PdfFileCreateInput
  ): Promise<PdfFileCreateInput> {
    return this.service.AddPdfFile(args);
  }

  @graphql.Mutation(() => String)
  async DeletePdfFile(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.DeletePdfFile(args);
  }

  @graphql.Mutation(() => PdfFileUpdateInput)
  async UpdatePdfFile(
    @graphql.Args()
    args: PdfFileUpdateInput
  ): Promise<PdfFileUpdateInput> {
    return this.service.UpdatePdfFile(args);
  }

  @graphql.Mutation(() => PdfFileUpdateInput)
  async UpdatePdfFilePascalCase(
    @graphql.Args()
    args: PdfFileUpdateInput
  ): Promise<PdfFileUpdateInput> {
    return this.service.UpdatePdfFilePascalCase(args);
  }

  @graphql.Mutation(() => PdfFile)
  async UpdatePdfFileWithPascalCase(
    @graphql.Args()
    args: PdfFileUpdatePascalInput
  ): Promise<PdfFile> {
    return this.service.UpdatePdfFileWithPascalCase(args);
  }
}
